### ISSUE TITLE
유저 엔티티 관련 Enum 타입으로의 리팩터링 요청

### ISSUE THREAD

**Issue by ChoMinGi** [ApptiveDev/apptive-19th-malico-backend#34]
#### 1. 타입 안정성 문제
현재 Member 엔티티에서 gender, city, state 필드들이 문자열 형태로 구현되어 있습니다. 이로 인해 타입 안정성이 부족하고, 유효하지 않은 데이터의 입력 가능성이 증가합니다.
#### 2. 확장성 및 유지보수의 어려움
새로운 성별, 도시, 구(state) 가 추가될 때마다 코드를 수정해야 하는 번거로움이 있으며, 코드의 변경이 많아질수록 유지보수가 어려워집니다.
#### 3. 데이터 무결성
문자열 기반 데이터는 사용자의 잘못된 입력으로 인해 데이터 무결성이 저하될 위험이 있습니다.

### 제안 리팩터링[ Enum 클래스 도입]
gender, city, state 필드를 Enum 타입으로 리팩터링하여 타입 안정성을 제공하고, 유효하지 않은 값의 입력을 방지합니다. Enum을 사용하면 사전에 정의된 값들만 사용할 수 있어 데이터 무결성을 향상시킬 수 있습니다.
### 기대 효과
1. 유지보수성 향상: 새로운 성별, 도시, 구를 추가할 때 Enum 클래스에만 추가하면 되므로, 유지보수성이 향상됩니다.
2. 코드 가독성 향상: Enum을 사용하면 코드가 더 명확하고 가독성이 좋아져, 코드를 이해하고 수정하기 쉬워집니다.

## 구현 예시
1. Gender Enum 클래스 생성: MALE, FEMALE, OTHER 등 성별을 나타내는 상수를 정의합니다.
2. City Enum 클래스 생성: 가능한 도시 목록을 상수로 정의합니다.
3. State Enum 클래스 생성: 구/시(state)를 나타내는 상수를 정의합니다.

```
public enum Gender {
    MALE, FEMALE, OTHER;
}

public enum City {
    SEOUL, BUSAN, DAEGU, ...;
}

public enum State {
    GWANGJU, JEONJU, ...;
}
```

### 엔티티 변경
기존의 Member 엔티티 내 gender, city, state 필드를 Enum 타입으로 변경합니다.

```
@Entity
@Table(name = "members", schema = "marico")
public class Member implements UserDetails {
    // ... 기존 필드 ...

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Gender gender;

    @Enumerated(EnumType.STRING)
    private City city;

    @Enumerated(EnumType.STRING)
    private State state;

}

```

#### DB에는 Enumerated옵션(다른 옵션은 없을까요?) 에 따라서 MALE 인 경우 MALE 이라고 저장이 되어집니다.
하지만 프론트사이드에서 "남성" 으로 달라고 할때는 어떻게 할까요?
```
public enum Gender {
    MALE("남성"), FEMALE("여성"), OTHER("기타");

    private final String displayName;

    // Constructor
    Gender(String displayName) {
        this.displayName = displayName;
    }

    // displayName 반환 메서드
    public String getDisplayName() {
        return displayName;
    }

    // 프론트엔드에서 받은 문자열을 Enum으로 변환하는 메서드
    public static Gender fromDisplayName(String displayName) {
        for (Gender gender : Gender.values()) {
            if (gender.getDisplayName().equals(displayName)) {
                return gender;
            }
        }
        throw new IllegalArgumentException("적절하지 않은 성별 입니다. " + displayName);
    }
}
```

이제는 회원 가입시 프론트에서 "남성" 을 보내주면 db에 Enum 형식으로 저장이 되고 MALE 로 표시되게 됩니다. 또한 출력시에도 Gender.MALE.getDisplayName() 로 보내주게 된다면 String 타입의 "남성"이라고 작성되게됩니다.

**Comment by ChoMinGi** [comment]
@JunHyeong-99 @JieunYume

**Comment by JieunYume** [comment]
오.. 찝찝하지만 그냥 넘어갔던 부분이었는데 찝어서 알려주셔서 감사합니다!! 리팩토링할 때 참고하겠습니다
